#!/bin/sh

# make sure that boot2docker is running first of all
boot2docker up

# start up db from base postgres image
docker run -d --name db \
  -v "/etc/postgresql" \
  -v "/var/log/postgresql" \
  -v "/var/lib/postgresql" \
  -p 5432:5432 \
  postgres:9.4.1
# no need to forcibly delete, can just hook up to it when it's up
docker start db

# build any new changes to the image
cd ~/sonar/web/docker/
docker build -t local/web .
# delete the old image
# TODO: don't delete if there are no changes
docker rm -f web
# start the new image
docker run -d --name web \
  -v ~/sonar/web:/var/src \
  -p 3000:80 -p 3443:443 -p 3001:3001 \
  --link db:db \
  -e "DATABASE_URL=postgres://postgres@db:5432/postgres" \
  -e "SECRET_KEY_BASE=bd75f41c7a4684b94f4ef0cafceb0966293a5b43c2dcf3bed76bbe085c0ec0ea58392ecfdd72f341ef3ea558d8fe3b86bd61bb15955302c675acc8b5fa073823" \
  local/web \
  /sbin/my_init -- sh -c '/etc/my_startup/start_rsync.sh && /etc/my_startup/start_unicorn.sh'

docker logs -f web
