#!/bin/sh

# make sure that boot2docker is running first of all
boot2docker up

# start up db from base postgres image
docker run -d --name db \
  -v "/etc/postgresql" \
  -v "/var/log/postgresql" \
  -v "/var/lib/postgresql" \
  -p 5432:5432 \
  postgres:9.4.1
# no need to forcibly delete, can just hook up to it when it's up
# TODO: hide error message if it's already running => check docker ps?
docker start db

docker run -d --name redis \
  -p 6379:6379 \
  redis:2.8 \
  redis-server --appendonly yes
docker start redis

# build any new changes to the image
cd ~/sonar/web/docker
docker build -t local/web .
# delete the old image
# TODO: don't delete if there are no changes
docker rm -f web
# start the new image
docker run -d --name web \
  -v ~/sonar/web:/var/src \
  -p 3000:80 -p 3443:443 -p 3001:3001 \
  --link db:db \
  --link redis:redis \
  -e "DATABASE_URL=postgres://postgres@db:5432/postgres" \
  -e "SECRET_KEY_BASE=bd75f41c7a4684b94f4ef0cafceb0966293a5b43c2dcf3bed76bbe085c0ec0ea58392ecfdd72f341ef3ea558d8fe3b86bd61bb15955302c675acc8b5fa073823" \
  -e "RAILS_RESQUE_REDIS=redis://redis:6379/0" \
  local/web \
#  /sbin/my_init -- sh -c '/etc/my_startup/start_bundle.sh && /etc/my_startup/start_rsync.sh && /etc/my_startup/start_thin.sh'

# TODO: docker -it thin / byebug doesn't work correctly, so need to bash in and start thin manually
