#!/bin/sh

fswatch -0 ~/sonar | while read -d "" EVENT
  do
    #DIR=$(dirname "${EVENT}")
    #VAR_SRC_DIR=${DIR//*\/sonar\/web//var/src}
    #VAR_HOME_DIR=${DIR//*\/sonar\/web//home/app/webapp}
    #echo $VAR_SRC_DIR
    #echo $VAR_HOME_DIR
    docker exec web /etc/my_startup/start_rsync.sh
  done
