web_base_url: http://dockerhost:3000
video_base_url: http://videos.dev.engsonar.com.s3.amazonaws.com
sign_up_url: http://www.asksonar.com/sign-up
chrome_app_id: plkkekmhfkddjdfgphbbnklkopldedfb
sample_scenario_result_id: 1036380517

s3_access_key: 'AKIAJ7KCGXATBCIQWREQ'
s3_secret_key: 'ITzUCoL4Wq3ToQMKCc47VCetKE1hvApyyjqnhlD7'
s3_region: 'us-west-1'
s3_upload_bucket: 'upload.dev.engsonar.com'
s3_videos_bucket: 'videos.dev.engsonar.com'
s3_backup_bucket: 'backup.dev.engsonar.com'
