web_base_url: http://dockerhost:3000
#video_base_url: http://videos.dev.asksonar.com
video_base_url: http://videos.dev.engsonar.com.s3.amazonaws.com
sign_up_url: http://www.asksonar.com/sign-up
chrome_app_id: plkkekmhfkddjdfgphbbnklkopldedfb
#chrome_app_id: ifnadmakmckbjjhbnjcjpfeeljhhmgib
