web_base_url: https://my-local.asksonar.com
sign_up_url: https://www.asksonar.com/sign-up
external_url: https://www.asksonar.com/

s3_access_key: AKIAJ7KCGXATBCIQWREQ
s3_secret_key: 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
s3_region: us-west-1
s3_upload_bucket: upload.dev.engsonar.com
s3_videos_bucket: videos.dev.engsonar.com
s3_backup_bucket: backup.dev.engsonar.com

mixpanel_token: 288067b052c38b64cc6cce9374d93339

sparkpost_username: SMTP_Injection
sparkpost_api_key: 8b6b5872adcfdda8f84e0792e1b8573bc401c79f

google_browser_key: AIzaSyBU24uUE9_X9b7i3RQGtNgNzPTfs31Pla8
google_server_key: AIzaSyBzGgBahCZEkbyB_mpaS-WnLyyJdOUgrNw
