web_base_url: https://my.asksonar.com
video_base_url: https://s3-us-west-1.amazonaws.com/videos.asksonar.com
sign_up_url: https://www.asksonar.com/sign-up
external_url: https://www.asksonar.com/
chrome_app_id: ifnadmakmckbjjhbnjcjpfeeljhhmgib
sample_scenario_result_id: 1036380636

s3_access_key: AKIAJQSUTS47ULBM5I7A
s3_secret_key: ZInBlvHJIaNYzr569Vdn2UWFzzgJN4ZkafGF5FeK
s3_region: us-west-1
s3_upload_bucket: upload.asksonar.com
s3_videos_bucket: videos.asksonar.com
s3_backup_bucket: backup.asksonar.com

mixpanel_token: 32a9d9b381fa35fd2fdd8ad9c715656b

mandrill_username: jonathan@asksonar.com
mandrill_api_key: dLlB-4ejRCHpwjoTWY01eg
