#!/bin/bash
# Forwards the Unicorn stdout.log and stderr.log to the Docker logs.
set -e
if [[ -e /var/log/unicorn/stdout.log ]]; then
  exec tail -F /var/log/unicorn/stdout.log
else
  exec sleep 10
fi

if [[ -e /var/log/unicorn/stderr.log ]]; then
  exec tail -F /var/log/unicorn/stderr.log
else
  exec sleep 10
fi
